# Generated by Django 5.1.2 on 2025-04-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Download Link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.URLField(default='https://previously-moving-giraffe.ngrok-free.app/static/default_user.png'),
        ),
    ]
