# Generated by Django 5.1.2 on 2024-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommendation_backend', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='last name'),
        ),
    ]
