# Generated by Django 5.1.2 on 2025-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommendation_backend', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
