# Generated by Django 5.1.2 on 2025-03-05 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeinteraction',
            unique_together={('user', 'recipe')},
        ),
    ]
