# Generated by Django 5.1.2 on 2025-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeinteraction_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='metric_amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='metric_unitLong',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='metric_unitShort',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='metric_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='metric_unitLong',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='metric_unitShort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
