# Generated by Django 5.1.2 on 2025-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredient_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinteraction',
            name='last_viewed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
