# Generated by Django 5.1.2 on 2025-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeinteraction_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinteraction',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
