# Generated by Django 5.1.2 on 2025-03-15 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeinteraction_last_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinteraction',
            name='last_viewed_count_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipeinteraction',
            name='time_when_liked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeinteraction',
            name='time_when_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeinteraction',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
