# Generated by Django 5.1.2 on 2025-03-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeinteraction_last_viewed_count_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipe',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('follow', 'Follow'), ('system', 'System')], default='system', max_length=10),
            preserve_default=False,
        ),
    ]
