# Generated by Django 5.1.2 on 2025-04-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('system', 'System'), ('confirmation', 'Order Confirmation'), ('milestone', 'Milestone')], max_length=20),
        ),
    ]
