# Generated by Django 5.1.2 on 2025-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='user_dietary_restrictions', to='recipes.diet'),
        ),
    ]
